--
-- PostgreSQL database dump
--

\restrict mMRxh3BAdbek5EhWTJ5xfRH0FpiflxzQE9Dcf5VgEFG8yoIY08Tdenhl6fGfHOu

-- Dumped from database version 17.6
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

-- CREATE SCHEMA public;   -- 제거: Supabase 신규 프로젝트에 public 스키마 기본 존재 → "already exists" 충돌 방지


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


--
-- Name: plan_tier; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.plan_tier AS ENUM (
    'free',
    'trial',
    'pro',
    'enterprise'
);


ALTER TYPE public.plan_tier OWNER TO postgres;

--
-- Name: current_tenant_ids(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.current_tenant_ids() RETURNS SETOF uuid
    LANGUAGE sql STABLE SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
  select tm.tenant_id
  from public.tenant_members tm
  where tm.user_id = auth.uid()
$$;


ALTER FUNCTION public.current_tenant_ids() OWNER TO postgres;

--
-- Name: handle_new_user(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.handle_new_user() RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
begin
  insert into public.profiles (id, email) values (new.id, new.email)
  on conflict (id) do nothing;
  return new;
end;
$$;


ALTER FUNCTION public.handle_new_user() OWNER TO postgres;

--
-- Name: is_admin(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.is_admin() RETURNS boolean
    LANGUAGE sql STABLE SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
  select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin');
$$;


ALTER FUNCTION public.is_admin() OWNER TO postgres;

--
-- Name: set_tenant_id_from_user(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.set_tenant_id_from_user() RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
begin
  if new.tenant_id is null then
    select tm.tenant_id
      into new.tenant_id
      from public.tenant_members tm
      join public.tenants        t on t.id = tm.tenant_id
     where tm.user_id = auth.uid()
     order by t.created_at asc, tm.tenant_id asc
     limit 1;
  end if;
  return new;
end
$$;


ALTER FUNCTION public.set_tenant_id_from_user() OWNER TO postgres;

--
-- Name: set_updated_at(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.set_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
begin new.updated_at := now(); return new; end;
$$;


ALTER FUNCTION public.set_updated_at() OWNER TO postgres;

--
-- Name: update_updated_at_column(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.update_updated_at_column() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;


ALTER FUNCTION public.update_updated_at_column() OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: create_drug_lots.sql; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."create_drug_lots.sql" (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public."create_drug_lots.sql" OWNER TO postgres;

--
-- Name: create_drug_lots.sql_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."create_drug_lots.sql" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."create_drug_lots.sql_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: drug_discontinuation; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.drug_discontinuation (
    id bigint NOT NULL,
    product_code text,
    drug_name text,
    manufacturer text,
    discontinuation_date date,
    discontinuation_reason text,
    alternative_drug text,
    data_source text DEFAULT 'HIRA_생산중단'::text,
    created_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.drug_discontinuation OWNER TO postgres;

--
-- Name: drug_discontinuation_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.drug_discontinuation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.drug_discontinuation_id_seq OWNER TO postgres;

--
-- Name: drug_discontinuation_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.drug_discontinuation_id_seq OWNED BY public.drug_discontinuation.id;


--
-- Name: drug_harmful; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.drug_harmful (
    id bigint NOT NULL,
    product_code text,
    drug_name text,
    manufacturer text,
    harmful_date date,
    harmful_reason text,
    risk_level integer,
    action_required text,
    data_source text DEFAULT 'HIRA_위해의약품'::text,
    created_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.drug_harmful OWNER TO postgres;

--
-- Name: drug_harmful_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.drug_harmful_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.drug_harmful_id_seq OWNER TO postgres;

--
-- Name: drug_harmful_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.drug_harmful_id_seq OWNED BY public.drug_harmful.id;


--
-- Name: drug_master; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.drug_master (
    id bigint NOT NULL,
    main_code text,
    product_code text,
    standard_code text,
    atc_code text,
    drug_name text NOT NULL,
    generic_name text,
    ingredient_kr text,
    ingredient_en text,
    manufacturer text,
    dosage_form_code text,
    dosage_form text,
    strength numeric,
    unit text,
    specification text,
    route text,
    edi_price numeric(10,2),
    max_price numeric(10,2),
    apply_date date,
    drug_class text,
    insurance_type text,
    rx_type text,
    storage_method text,
    has_age_contraindication boolean DEFAULT false,
    has_pregnancy_contraindication boolean DEFAULT false,
    has_elderly_caution boolean DEFAULT false,
    is_discontinued boolean DEFAULT false,
    is_harmful boolean DEFAULT false,
    harmful_risk_level integer,
    search_text text,
    data_source text,
    last_verified timestamp without time zone DEFAULT now(),
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.drug_master OWNER TO postgres;

--
-- Name: drug_master_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.drug_master_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.drug_master_id_seq OWNER TO postgres;

--
-- Name: drug_master_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.drug_master_id_seq OWNED BY public.drug_master.id;


--
-- Name: drug_status_alerts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.drug_status_alerts (
    id bigint NOT NULL,
    internal_drug_code text,
    product_code text,
    drug_name text,
    alert_type text,
    severity text,
    message text,
    detected_at timestamp without time zone DEFAULT now(),
    acknowledged boolean DEFAULT false,
    acknowledged_at timestamp without time zone,
    acknowledged_by text
);


ALTER TABLE public.drug_status_alerts OWNER TO postgres;

--
-- Name: drug_status_alerts_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.drug_status_alerts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.drug_status_alerts_id_seq OWNER TO postgres;

--
-- Name: drug_status_alerts_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.drug_status_alerts_id_seq OWNED BY public.drug_status_alerts.id;


--
-- Name: drug_vocab; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.drug_vocab (
    axis text NOT NULL,
    code text NOT NULL,
    label text NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    note text
);


ALTER TABLE public.drug_vocab OWNER TO postgres;

--
-- Name: TABLE drug_vocab; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.drug_vocab IS '약품 통제 어휘 7종(구분·마약구분·급여·복합단일·전문일반·보관방법·상태). 전 테넌트 공유 reference. 가이드 §6-5 기준.';


--
-- Name: drugs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.drugs (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    drug_code text DEFAULT ''::text NOT NULL,
    drug_name text NOT NULL,
    category text DEFAULT ''::text,
    ingredient_en text DEFAULT ''::text,
    ingredient_kr text DEFAULT ''::text,
    indication text DEFAULT ''::text,
    manufacturer text DEFAULT ''::text,
    standard text DEFAULT ''::text,
    unit text DEFAULT ''::text,
    price_pack integer DEFAULT 0,
    price_unit integer DEFAULT 0,
    expiry_date date,
    storage_method text DEFAULT ''::text,
    status text DEFAULT '사용'::text,
    storage_location text DEFAULT ''::text,
    last_in_date date,
    memo text DEFAULT ''::text,
    is_narcotic boolean DEFAULT false,
    narcotic_type text DEFAULT ''::text,
    standard_code text DEFAULT ''::text,
    created_at timestamp with time zone DEFAULT now(),
    current_qty integer DEFAULT 0,
    current_amount bigint DEFAULT 0,
    edi_code text DEFAULT ''::text,
    edi_price integer DEFAULT 0,
    lot_no text DEFAULT ''::text,
    insurance_code text DEFAULT ''::text,
    insurance_type text DEFAULT '보험'::text,
    dosage text DEFAULT ''::text,
    side_effects text DEFAULT ''::text,
    safety_stock integer DEFAULT 0,
    max_stock integer DEFAULT 0,
    efficacy text DEFAULT ''::text,
    specification text DEFAULT ''::text,
    price_per_bottle integer DEFAULT 0,
    notes text DEFAULT ''::text,
    monthly_avg integer DEFAULT 0,
    prev_year_usage integer DEFAULT 0,
    recent_3m_usage integer DEFAULT 0,
    last_used_dept text,
    last_used_date date,
    tenant_id uuid,
    compound_type text,
    prescription_type text
);


ALTER TABLE public.drugs OWNER TO postgres;

--
-- Name: COLUMN drugs.compound_type; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.drugs.compound_type IS '복합/단일 — drug_vocab(axis=compound). NULL=미분류(P1-3 보강).';


--
-- Name: COLUMN drugs.prescription_type; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.drugs.prescription_type IS '전문/일반 정규화 — drug_vocab(axis=rx_class). NULL=미분류(P1-3 보강).';


--
-- Name: dur_age_contraindication; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.dur_age_contraindication (
    id bigint NOT NULL,
    main_code text,
    product_code text,
    drug_name text,
    generic_name text,
    contraindication_age text,
    contraindication_detail text,
    reason text,
    data_source text DEFAULT 'DUR'::text,
    created_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.dur_age_contraindication OWNER TO postgres;

--
-- Name: dur_age_contraindication_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.dur_age_contraindication_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.dur_age_contraindication_id_seq OWNER TO postgres;

--
-- Name: dur_age_contraindication_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.dur_age_contraindication_id_seq OWNED BY public.dur_age_contraindication.id;


--
-- Name: dur_elderly_caution; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.dur_elderly_caution (
    id bigint NOT NULL,
    main_code text,
    product_code text,
    drug_name text,
    generic_name text,
    caution_type text,
    caution_detail text,
    risk_description text,
    data_source text DEFAULT 'DUR'::text,
    created_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.dur_elderly_caution OWNER TO postgres;

--
-- Name: dur_elderly_caution_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.dur_elderly_caution_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.dur_elderly_caution_id_seq OWNER TO postgres;

--
-- Name: dur_elderly_caution_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.dur_elderly_caution_id_seq OWNED BY public.dur_elderly_caution.id;


--
-- Name: dur_pregnancy_contraindication; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.dur_pregnancy_contraindication (
    id bigint NOT NULL,
    main_code text,
    product_code text,
    drug_name text,
    generic_name text,
    fda_category text,
    contraindication_detail text,
    warning text,
    data_source text DEFAULT 'DUR'::text,
    created_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.dur_pregnancy_contraindication OWNER TO postgres;

--
-- Name: dur_pregnancy_contraindication_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.dur_pregnancy_contraindication_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.dur_pregnancy_contraindication_id_seq OWNER TO postgres;

--
-- Name: dur_pregnancy_contraindication_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.dur_pregnancy_contraindication_id_seq OWNED BY public.dur_pregnancy_contraindication.id;


--
-- Name: inventory_stock; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.inventory_stock (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    drug_code text NOT NULL,
    current_qty integer DEFAULT 0,
    current_amount bigint DEFAULT 0,
    safety_stock integer DEFAULT 0,
    max_stock integer DEFAULT 0,
    prev_year_usage integer DEFAULT 0,
    recent_3m_usage integer DEFAULT 0,
    monthly_avg numeric DEFAULT 0,
    stock_status text DEFAULT ''::text,
    order_alert text DEFAULT ''::text,
    updated_at timestamp with time zone DEFAULT now(),
    drug_name text DEFAULT ''::text,
    tenant_id uuid
);


ALTER TABLE public.inventory_stock OWNER TO postgres;

--
-- Name: monthly_snapshots; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.monthly_snapshots (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    drug_code text NOT NULL,
    snap_year integer NOT NULL,
    snap_month integer NOT NULL,
    opening_qty integer DEFAULT 0,
    opening_amount bigint DEFAULT 0,
    total_in_qty integer DEFAULT 0,
    total_in_amount bigint DEFAULT 0,
    subtotal_qty integer DEFAULT 0,
    subtotal_amount bigint DEFAULT 0,
    total_out_qty integer DEFAULT 0,
    total_out_amount bigint DEFAULT 0,
    total_disp_qty integer DEFAULT 0,
    total_ret_qty integer DEFAULT 0,
    closing_qty integer DEFAULT 0,
    closing_amount bigint DEFAULT 0,
    tenant_id uuid
);


ALTER TABLE public.monthly_snapshots OWNER TO postgres;

--
-- Name: profiles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.profiles (
    id uuid NOT NULL,
    email text,
    full_name text,
    phone text,
    dept text,
    "position" text,
    role text DEFAULT 'user'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.profiles OWNER TO postgres;

--
-- Name: tenant_members; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tenant_members (
    tenant_id uuid NOT NULL,
    user_id uuid NOT NULL,
    role text DEFAULT 'member'::text NOT NULL
);


ALTER TABLE public.tenant_members OWNER TO postgres;

--
-- Name: tenants; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tenants (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name text NOT NULL,
    slug text NOT NULL,
    plan public.plan_tier DEFAULT 'trial'::public.plan_tier NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.tenants OWNER TO postgres;

--
-- Name: transactions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.transactions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    drug_code text NOT NULL,
    type text NOT NULL,
    quantity integer NOT NULL,
    unit_price integer DEFAULT 0,
    total_amount bigint DEFAULT 0,
    lot_no text DEFAULT ''::text,
    expiry_date date,
    supplier text DEFAULT ''::text,
    reason text DEFAULT ''::text,
    handler text DEFAULT ''::text,
    approver text DEFAULT ''::text,
    process_status text DEFAULT ''::text,
    transaction_date date DEFAULT CURRENT_DATE,
    memo text DEFAULT ''::text,
    created_at timestamp with time zone DEFAULT now(),
    tenant_id uuid
);


ALTER TABLE public.transactions OWNER TO postgres;

--
-- Name: drug_discontinuation id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.drug_discontinuation ALTER COLUMN id SET DEFAULT nextval('public.drug_discontinuation_id_seq'::regclass);


--
-- Name: drug_harmful id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.drug_harmful ALTER COLUMN id SET DEFAULT nextval('public.drug_harmful_id_seq'::regclass);


--
-- Name: drug_master id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.drug_master ALTER COLUMN id SET DEFAULT nextval('public.drug_master_id_seq'::regclass);


--
-- Name: drug_status_alerts id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.drug_status_alerts ALTER COLUMN id SET DEFAULT nextval('public.drug_status_alerts_id_seq'::regclass);


--
-- Name: dur_age_contraindication id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dur_age_contraindication ALTER COLUMN id SET DEFAULT nextval('public.dur_age_contraindication_id_seq'::regclass);


--
-- Name: dur_elderly_caution id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dur_elderly_caution ALTER COLUMN id SET DEFAULT nextval('public.dur_elderly_caution_id_seq'::regclass);


--
-- Name: dur_pregnancy_contraindication id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dur_pregnancy_contraindication ALTER COLUMN id SET DEFAULT nextval('public.dur_pregnancy_contraindication_id_seq'::regclass);


--
-- Name: create_drug_lots.sql create_drug_lots.sql_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."create_drug_lots.sql"
    ADD CONSTRAINT "create_drug_lots.sql_pkey" PRIMARY KEY (id);


--
-- Name: drug_discontinuation drug_discontinuation_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.drug_discontinuation
    ADD CONSTRAINT drug_discontinuation_pkey PRIMARY KEY (id);


--
-- Name: drug_harmful drug_harmful_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.drug_harmful
    ADD CONSTRAINT drug_harmful_pkey PRIMARY KEY (id);


--
-- Name: drug_master drug_master_main_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.drug_master
    ADD CONSTRAINT drug_master_main_code_key UNIQUE (main_code);


--
-- Name: drug_master drug_master_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.drug_master
    ADD CONSTRAINT drug_master_pkey PRIMARY KEY (id);


--
-- Name: drug_status_alerts drug_status_alerts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.drug_status_alerts
    ADD CONSTRAINT drug_status_alerts_pkey PRIMARY KEY (id);


--
-- Name: drug_vocab drug_vocab_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.drug_vocab
    ADD CONSTRAINT drug_vocab_pkey PRIMARY KEY (axis, code);


--
-- Name: drugs drugs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.drugs
    ADD CONSTRAINT drugs_pkey PRIMARY KEY (id);


--
-- Name: dur_age_contraindication dur_age_contraindication_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dur_age_contraindication
    ADD CONSTRAINT dur_age_contraindication_pkey PRIMARY KEY (id);


--
-- Name: dur_elderly_caution dur_elderly_caution_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dur_elderly_caution
    ADD CONSTRAINT dur_elderly_caution_pkey PRIMARY KEY (id);


--
-- Name: dur_pregnancy_contraindication dur_pregnancy_contraindication_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dur_pregnancy_contraindication
    ADD CONSTRAINT dur_pregnancy_contraindication_pkey PRIMARY KEY (id);


--
-- Name: inventory_stock inventory_stock_drug_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventory_stock
    ADD CONSTRAINT inventory_stock_drug_code_key UNIQUE (drug_code);


--
-- Name: inventory_stock inventory_stock_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventory_stock
    ADD CONSTRAINT inventory_stock_pkey PRIMARY KEY (id);


--
-- Name: monthly_snapshots monthly_snapshots_drug_code_snap_year_snap_month_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.monthly_snapshots
    ADD CONSTRAINT monthly_snapshots_drug_code_snap_year_snap_month_key UNIQUE (drug_code, snap_year, snap_month);


--
-- Name: monthly_snapshots monthly_snapshots_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.monthly_snapshots
    ADD CONSTRAINT monthly_snapshots_pkey PRIMARY KEY (id);


--
-- Name: profiles profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT profiles_pkey PRIMARY KEY (id);


--
-- Name: tenant_members tenant_members_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tenant_members
    ADD CONSTRAINT tenant_members_pkey PRIMARY KEY (tenant_id, user_id);


--
-- Name: tenants tenants_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tenants
    ADD CONSTRAINT tenants_pkey PRIMARY KEY (id);


--
-- Name: tenants tenants_slug_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tenants
    ADD CONSTRAINT tenants_slug_key UNIQUE (slug);


--
-- Name: transactions transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_pkey PRIMARY KEY (id);


--
-- Name: idx_alerts_acknowledged; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_alerts_acknowledged ON public.drug_status_alerts USING btree (acknowledged);


--
-- Name: idx_alerts_internal_code; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_alerts_internal_code ON public.drug_status_alerts USING btree (internal_drug_code);


--
-- Name: idx_alerts_severity; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_alerts_severity ON public.drug_status_alerts USING btree (severity);


--
-- Name: idx_alerts_type; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_alerts_type ON public.drug_status_alerts USING btree (alert_type);


--
-- Name: idx_discontinuation_name; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_discontinuation_name ON public.drug_discontinuation USING btree (drug_name);


--
-- Name: idx_discontinuation_product_code; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_discontinuation_product_code ON public.drug_discontinuation USING btree (product_code);


--
-- Name: idx_drug_master_flags; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_drug_master_flags ON public.drug_master USING btree (is_discontinued, is_harmful, has_age_contraindication, has_pregnancy_contraindication);


--
-- Name: idx_drug_master_generic; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_drug_master_generic ON public.drug_master USING btree (generic_name);


--
-- Name: idx_drug_master_manufacturer; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_drug_master_manufacturer ON public.drug_master USING btree (manufacturer);


--
-- Name: idx_drug_master_name; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_drug_master_name ON public.drug_master USING btree (drug_name);


--
-- Name: idx_drug_master_product_code; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_drug_master_product_code ON public.drug_master USING btree (product_code);


--
-- Name: idx_drug_master_search; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_drug_master_search ON public.drug_master USING gin (to_tsvector('simple'::regconfig, search_text));


--
-- Name: idx_dur_age_main_code; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_dur_age_main_code ON public.dur_age_contraindication USING btree (main_code);


--
-- Name: idx_dur_elderly_main_code; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_dur_elderly_main_code ON public.dur_elderly_caution USING btree (main_code);


--
-- Name: idx_dur_pregnancy_main_code; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_dur_pregnancy_main_code ON public.dur_pregnancy_contraindication USING btree (main_code);


--
-- Name: idx_harmful_name; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_harmful_name ON public.drug_harmful USING btree (drug_name);


--
-- Name: idx_harmful_product_code; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_harmful_product_code ON public.drug_harmful USING btree (product_code);


--
-- Name: idx_harmful_risk_level; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_harmful_risk_level ON public.drug_harmful USING btree (risk_level);


--
-- Name: profiles profiles_set_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER profiles_set_updated_at BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: drugs trg_set_tenant_id; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_set_tenant_id BEFORE INSERT ON public.drugs FOR EACH ROW EXECUTE FUNCTION public.set_tenant_id_from_user();


--
-- Name: inventory_stock trg_set_tenant_id; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_set_tenant_id BEFORE INSERT ON public.inventory_stock FOR EACH ROW EXECUTE FUNCTION public.set_tenant_id_from_user();


--
-- Name: monthly_snapshots trg_set_tenant_id; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_set_tenant_id BEFORE INSERT ON public.monthly_snapshots FOR EACH ROW EXECUTE FUNCTION public.set_tenant_id_from_user();


--
-- Name: transactions trg_set_tenant_id; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_set_tenant_id BEFORE INSERT ON public.transactions FOR EACH ROW EXECUTE FUNCTION public.set_tenant_id_from_user();


--
-- Name: drug_master update_drug_master_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER update_drug_master_updated_at BEFORE UPDATE ON public.drug_master FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


--
-- Name: drugs drugs_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.drugs
    ADD CONSTRAINT drugs_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);


--
-- Name: dur_age_contraindication dur_age_contraindication_main_code_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dur_age_contraindication
    ADD CONSTRAINT dur_age_contraindication_main_code_fkey FOREIGN KEY (main_code) REFERENCES public.drug_master(main_code) ON DELETE CASCADE;


--
-- Name: dur_elderly_caution dur_elderly_caution_main_code_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dur_elderly_caution
    ADD CONSTRAINT dur_elderly_caution_main_code_fkey FOREIGN KEY (main_code) REFERENCES public.drug_master(main_code) ON DELETE CASCADE;


--
-- Name: dur_pregnancy_contraindication dur_pregnancy_contraindication_main_code_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dur_pregnancy_contraindication
    ADD CONSTRAINT dur_pregnancy_contraindication_main_code_fkey FOREIGN KEY (main_code) REFERENCES public.drug_master(main_code) ON DELETE CASCADE;


--
-- Name: inventory_stock inventory_stock_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventory_stock
    ADD CONSTRAINT inventory_stock_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);


--
-- Name: monthly_snapshots monthly_snapshots_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.monthly_snapshots
    ADD CONSTRAINT monthly_snapshots_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);


--
-- Name: profiles profiles_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;


--
-- Name: tenant_members tenant_members_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tenant_members
    ADD CONSTRAINT tenant_members_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE;


--
-- Name: tenant_members tenant_members_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tenant_members
    ADD CONSTRAINT tenant_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;


--
-- Name: transactions transactions_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);


--
-- Name: create_drug_lots.sql; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public."create_drug_lots.sql" ENABLE ROW LEVEL SECURITY;

--
-- Name: drug_vocab; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.drug_vocab ENABLE ROW LEVEL SECURITY;

--
-- Name: drug_vocab drug_vocab_select_authenticated; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY drug_vocab_select_authenticated ON public.drug_vocab FOR SELECT TO authenticated USING (true);


--
-- Name: drugs; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.drugs ENABLE ROW LEVEL SECURITY;

--
-- Name: drugs drugs_delete_admin_own_tenant; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY drugs_delete_admin_own_tenant ON public.drugs FOR DELETE USING (((tenant_id IN ( SELECT public.current_tenant_ids() AS current_tenant_ids)) AND (EXISTS ( SELECT 1
   FROM public.tenant_members tm
  WHERE ((tm.user_id = auth.uid()) AND (tm.tenant_id = drugs.tenant_id) AND (tm.role = ANY (ARRAY['owner'::text, 'admin'::text])))))));


--
-- Name: drugs drugs_insert_own_tenant; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY drugs_insert_own_tenant ON public.drugs FOR INSERT WITH CHECK ((tenant_id IN ( SELECT public.current_tenant_ids() AS current_tenant_ids)));


--
-- Name: drugs drugs_select_own_tenant; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY drugs_select_own_tenant ON public.drugs FOR SELECT USING ((tenant_id IN ( SELECT public.current_tenant_ids() AS current_tenant_ids)));


--
-- Name: drugs drugs_update_own_tenant; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY drugs_update_own_tenant ON public.drugs FOR UPDATE USING ((tenant_id IN ( SELECT public.current_tenant_ids() AS current_tenant_ids))) WITH CHECK ((tenant_id IN ( SELECT public.current_tenant_ids() AS current_tenant_ids)));


--
-- Name: inventory_stock; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.inventory_stock ENABLE ROW LEVEL SECURITY;

--
-- Name: inventory_stock inventory_stock_insert_own_tenant; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY inventory_stock_insert_own_tenant ON public.inventory_stock FOR INSERT WITH CHECK ((tenant_id IN ( SELECT public.current_tenant_ids() AS current_tenant_ids)));


--
-- Name: inventory_stock inventory_stock_select_own_tenant; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY inventory_stock_select_own_tenant ON public.inventory_stock FOR SELECT USING ((tenant_id IN ( SELECT public.current_tenant_ids() AS current_tenant_ids)));


--
-- Name: inventory_stock inventory_stock_update_own_tenant; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY inventory_stock_update_own_tenant ON public.inventory_stock FOR UPDATE USING ((tenant_id IN ( SELECT public.current_tenant_ids() AS current_tenant_ids))) WITH CHECK ((tenant_id IN ( SELECT public.current_tenant_ids() AS current_tenant_ids)));


--
-- Name: monthly_snapshots; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.monthly_snapshots ENABLE ROW LEVEL SECURITY;

--
-- Name: monthly_snapshots monthly_snapshots_insert_own_tenant; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY monthly_snapshots_insert_own_tenant ON public.monthly_snapshots FOR INSERT WITH CHECK ((tenant_id IN ( SELECT public.current_tenant_ids() AS current_tenant_ids)));


--
-- Name: monthly_snapshots monthly_snapshots_select_own_tenant; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY monthly_snapshots_select_own_tenant ON public.monthly_snapshots FOR SELECT USING ((tenant_id IN ( SELECT public.current_tenant_ids() AS current_tenant_ids)));


--
-- Name: monthly_snapshots monthly_snapshots_update_own_tenant; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY monthly_snapshots_update_own_tenant ON public.monthly_snapshots FOR UPDATE USING ((tenant_id IN ( SELECT public.current_tenant_ids() AS current_tenant_ids))) WITH CHECK ((tenant_id IN ( SELECT public.current_tenant_ids() AS current_tenant_ids)));


--
-- Name: profiles; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

--
-- Name: profiles profiles_select_admin_all; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY profiles_select_admin_all ON public.profiles FOR SELECT USING (public.is_admin());


--
-- Name: profiles profiles_select_own; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY profiles_select_own ON public.profiles FOR SELECT USING ((auth.uid() = id));


--
-- Name: profiles profiles_update_own; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY profiles_update_own ON public.profiles FOR UPDATE USING ((auth.uid() = id));


--
-- Name: tenant_members; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.tenant_members ENABLE ROW LEVEL SECURITY;

--
-- Name: tenants; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.tenants ENABLE ROW LEVEL SECURITY;

--
-- Name: transactions; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;

--
-- Name: transactions transactions_insert_own_tenant; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY transactions_insert_own_tenant ON public.transactions FOR INSERT WITH CHECK ((tenant_id IN ( SELECT public.current_tenant_ids() AS current_tenant_ids)));


--
-- Name: transactions transactions_select_own_tenant; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY transactions_select_own_tenant ON public.transactions FOR SELECT USING ((tenant_id IN ( SELECT public.current_tenant_ids() AS current_tenant_ids)));


--
-- Name: transactions transactions_update_own_tenant; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY transactions_update_own_tenant ON public.transactions FOR UPDATE USING ((tenant_id IN ( SELECT public.current_tenant_ids() AS current_tenant_ids))) WITH CHECK ((tenant_id IN ( SELECT public.current_tenant_ids() AS current_tenant_ids)));


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT USAGE ON SCHEMA public TO postgres;
GRANT USAGE ON SCHEMA public TO anon;
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT USAGE ON SCHEMA public TO service_role;


--
-- Name: FUNCTION current_tenant_ids(); Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON FUNCTION public.current_tenant_ids() TO anon;
GRANT ALL ON FUNCTION public.current_tenant_ids() TO authenticated;
GRANT ALL ON FUNCTION public.current_tenant_ids() TO service_role;


--
-- Name: FUNCTION handle_new_user(); Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON FUNCTION public.handle_new_user() TO anon;
GRANT ALL ON FUNCTION public.handle_new_user() TO authenticated;
GRANT ALL ON FUNCTION public.handle_new_user() TO service_role;


--
-- Name: FUNCTION is_admin(); Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON FUNCTION public.is_admin() TO anon;
GRANT ALL ON FUNCTION public.is_admin() TO authenticated;
GRANT ALL ON FUNCTION public.is_admin() TO service_role;


--
-- Name: FUNCTION set_tenant_id_from_user(); Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON FUNCTION public.set_tenant_id_from_user() TO anon;
GRANT ALL ON FUNCTION public.set_tenant_id_from_user() TO authenticated;
GRANT ALL ON FUNCTION public.set_tenant_id_from_user() TO service_role;


--
-- Name: FUNCTION set_updated_at(); Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON FUNCTION public.set_updated_at() TO anon;
GRANT ALL ON FUNCTION public.set_updated_at() TO authenticated;
GRANT ALL ON FUNCTION public.set_updated_at() TO service_role;


--
-- Name: FUNCTION update_updated_at_column(); Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON FUNCTION public.update_updated_at_column() TO anon;
GRANT ALL ON FUNCTION public.update_updated_at_column() TO authenticated;
GRANT ALL ON FUNCTION public.update_updated_at_column() TO service_role;


--
-- Name: TABLE "create_drug_lots.sql"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public."create_drug_lots.sql" TO anon;
GRANT ALL ON TABLE public."create_drug_lots.sql" TO authenticated;
GRANT ALL ON TABLE public."create_drug_lots.sql" TO service_role;


--
-- Name: SEQUENCE "create_drug_lots.sql_id_seq"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public."create_drug_lots.sql_id_seq" TO anon;
GRANT ALL ON SEQUENCE public."create_drug_lots.sql_id_seq" TO authenticated;
GRANT ALL ON SEQUENCE public."create_drug_lots.sql_id_seq" TO service_role;


--
-- Name: TABLE drug_discontinuation; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.drug_discontinuation TO anon;
GRANT ALL ON TABLE public.drug_discontinuation TO authenticated;
GRANT ALL ON TABLE public.drug_discontinuation TO service_role;


--
-- Name: SEQUENCE drug_discontinuation_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.drug_discontinuation_id_seq TO anon;
GRANT ALL ON SEQUENCE public.drug_discontinuation_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.drug_discontinuation_id_seq TO service_role;


--
-- Name: TABLE drug_harmful; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.drug_harmful TO anon;
GRANT ALL ON TABLE public.drug_harmful TO authenticated;
GRANT ALL ON TABLE public.drug_harmful TO service_role;


--
-- Name: SEQUENCE drug_harmful_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.drug_harmful_id_seq TO anon;
GRANT ALL ON SEQUENCE public.drug_harmful_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.drug_harmful_id_seq TO service_role;


--
-- Name: TABLE drug_master; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.drug_master TO anon;
GRANT ALL ON TABLE public.drug_master TO authenticated;
GRANT ALL ON TABLE public.drug_master TO service_role;


--
-- Name: SEQUENCE drug_master_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.drug_master_id_seq TO anon;
GRANT ALL ON SEQUENCE public.drug_master_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.drug_master_id_seq TO service_role;


--
-- Name: TABLE drug_status_alerts; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.drug_status_alerts TO anon;
GRANT ALL ON TABLE public.drug_status_alerts TO authenticated;
GRANT ALL ON TABLE public.drug_status_alerts TO service_role;


--
-- Name: SEQUENCE drug_status_alerts_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.drug_status_alerts_id_seq TO anon;
GRANT ALL ON SEQUENCE public.drug_status_alerts_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.drug_status_alerts_id_seq TO service_role;


--
-- Name: TABLE drug_vocab; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.drug_vocab TO anon;
GRANT ALL ON TABLE public.drug_vocab TO authenticated;
GRANT ALL ON TABLE public.drug_vocab TO service_role;


--
-- Name: TABLE drugs; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.drugs TO anon;
GRANT ALL ON TABLE public.drugs TO authenticated;
GRANT ALL ON TABLE public.drugs TO service_role;


--
-- Name: TABLE dur_age_contraindication; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.dur_age_contraindication TO anon;
GRANT ALL ON TABLE public.dur_age_contraindication TO authenticated;
GRANT ALL ON TABLE public.dur_age_contraindication TO service_role;


--
-- Name: SEQUENCE dur_age_contraindication_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.dur_age_contraindication_id_seq TO anon;
GRANT ALL ON SEQUENCE public.dur_age_contraindication_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.dur_age_contraindication_id_seq TO service_role;


--
-- Name: TABLE dur_elderly_caution; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.dur_elderly_caution TO anon;
GRANT ALL ON TABLE public.dur_elderly_caution TO authenticated;
GRANT ALL ON TABLE public.dur_elderly_caution TO service_role;


--
-- Name: SEQUENCE dur_elderly_caution_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.dur_elderly_caution_id_seq TO anon;
GRANT ALL ON SEQUENCE public.dur_elderly_caution_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.dur_elderly_caution_id_seq TO service_role;


--
-- Name: TABLE dur_pregnancy_contraindication; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.dur_pregnancy_contraindication TO anon;
GRANT ALL ON TABLE public.dur_pregnancy_contraindication TO authenticated;
GRANT ALL ON TABLE public.dur_pregnancy_contraindication TO service_role;


--
-- Name: SEQUENCE dur_pregnancy_contraindication_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.dur_pregnancy_contraindication_id_seq TO anon;
GRANT ALL ON SEQUENCE public.dur_pregnancy_contraindication_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.dur_pregnancy_contraindication_id_seq TO service_role;


--
-- Name: TABLE inventory_stock; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.inventory_stock TO anon;
GRANT ALL ON TABLE public.inventory_stock TO authenticated;
GRANT ALL ON TABLE public.inventory_stock TO service_role;


--
-- Name: TABLE monthly_snapshots; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.monthly_snapshots TO anon;
GRANT ALL ON TABLE public.monthly_snapshots TO authenticated;
GRANT ALL ON TABLE public.monthly_snapshots TO service_role;


--
-- Name: TABLE profiles; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.profiles TO anon;
GRANT ALL ON TABLE public.profiles TO authenticated;
GRANT ALL ON TABLE public.profiles TO service_role;


--
-- Name: TABLE tenant_members; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.tenant_members TO anon;
GRANT ALL ON TABLE public.tenant_members TO authenticated;
GRANT ALL ON TABLE public.tenant_members TO service_role;


--
-- Name: TABLE tenants; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.tenants TO anon;
GRANT ALL ON TABLE public.tenants TO authenticated;
GRANT ALL ON TABLE public.tenants TO service_role;


--
-- Name: TABLE transactions; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.transactions TO anon;
GRANT ALL ON TABLE public.transactions TO authenticated;
GRANT ALL ON TABLE public.transactions TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO service_role;


--
-- PostgreSQL database dump complete
--

\unrestrict mMRxh3BAdbek5EhWTJ5xfRH0FpiflxzQE9Dcf5VgEFG8yoIY08Tdenhl6fGfHOu

